name: Job set up
description: Sets up the Java and Gradle
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'
        java-package: jdk
        cache: 'gradle'
