[versions]
agp = "8.2.2"
androidx-activityCompose = "1.8.2"
buildkonfig = "0.15.1"
compose = "1.6.7"
# Check latest at https://developer.android.com/jetpack/androidx/releases/compose-compiler
compose-compiler = "1.5.11"
compose-maps = "4.4.2"
# Check latest at https://github.com/JetBrains/compose-multiplatform/releases
compose-plugin = "1.6.2"
compose-windowSizeClass = "0.5.0"
kmpio = "0.1.6"
kotlin = "1.9.23"
kotlinx = "1.8.0"
kotlinx-datetime = "0.5.0"
kotlinx-json = "1.6.3"
ksoup = "0.1.2"
ktor = "2.3.10"
mapbox = "5.8.0"
multiplatform-settings = "1.1.1"
napier = "2.7.1"
okio = "3.9.0"
play-appupdate = "2.1.0"
play-instantapps = "18.0.1"
semver = "2.0.0"
sqldelight = "2.0.2"
voyager = "1.0.0"
zoomable = "1.6.1"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-maps-base = { module = "com.google.maps.android:maps-compose", version.ref = "compose-maps" }
compose-maps-utils = { module = "com.google.maps.android:maps-compose-utils", version.ref = "compose-maps" }
compose-windowSizeClass = { module = "dev.chrisbanes.material3:material3-window-size-class-multiplatform", version.ref = "compose-windowSizeClass" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
kmpio = { module = "io.github.skolson:kmp-io", version.ref = "kmpio" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json =  { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-json" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
mapbox-core = { module = "com.mapbox.mapboxsdk:mapbox-sdk-core", version.ref = "mapbox" }
mapbox-services = { module = "com.mapbox.mapboxsdk:mapbox-sdk-services", version.ref = "mapbox" }
multiplatformSettings-base = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatformSettings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatform-settings" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
play-appupdate = { module = "com.google.android.play:app-update-ktx", version.ref = "play-appupdate" }
play-instantapps = { module = "com.google.android.gms:play-services-instantapps", version.ref = "play-instantapps" }
semver = { module = "io.github.z4kn4fein:semver", version.ref = "semver" }
sqldelight-driver-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-driver-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-driver-sqlite = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-screenmodel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
zoomable = { module = "com.mxalbert.zoomable:zoomable", version.ref = "zoomable" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
