[versions]
agp = "8.7.3"
androidx-activityCompose = "1.9.3"
buildkonfig = "0.15.2"
compose-maps = "6.4.0"
compose-navigation = "2.8.0-alpha11"
# Check latest at https://github.com/JetBrains/compose-multiplatform/releases
compose-plugin = "1.8.0+dev1989"
compose-ui = "1.7.6"
compose-viewModel = "2.9.0+dev1955"
compose-windowSizeClass = "0.5.0"
kmpio = "0.1.6"
kotlin = "2.1.0"
kotlinx = "1.10.1"
kotlinx-datetime = "0.6.1"
kotlinx-json = "1.7.3"
kotlinx-io = "0.6.0"
ksoup = "0.2.1"
ktor = "3.0.3"
mapbox = "5.8.0"
multiplatform-settings = "1.3.0"
napier = "2.7.1"
play-appupdate = "2.1.0"
play-instantapps = "18.1.0"
semver = "2.0.0"
zoomable = "1.7.0-SNAPSHOT"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-maps-base = { module = "com.google.maps.android:maps-compose", version.ref = "compose-maps" }
compose-maps-utils = { module = "com.google.maps.android:maps-compose-utils", version.ref = "compose-maps" }
compose-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
compose-viewModel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-viewModel" }
compose-windowSizeClass = { module = "dev.chrisbanes.material3:material3-window-size-class-multiplatform", version.ref = "compose-windowSizeClass" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui" }
kmpio = { module = "io.github.skolson:kmp-io", version.ref = "kmpio" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-serialization-json =  { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-json" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
mapbox-core = { module = "com.mapbox.mapboxsdk:mapbox-sdk-core", version.ref = "mapbox" }
mapbox-services = { module = "com.mapbox.mapboxsdk:mapbox-sdk-services", version.ref = "mapbox" }
multiplatformSettings-base = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatformSettings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatform-settings" }
multiplatformSettings-makeObservable = { module = "com.russhwolf:multiplatform-settings-make-observable", version.ref = "multiplatform-settings" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
play-appupdate = { module = "com.google.android.play:app-update-ktx", version.ref = "play-appupdate" }
play-instantapps = { module = "com.google.android.gms:play-services-instantapps", version.ref = "play-instantapps" }
semver = { module = "io.github.z4kn4fein:semver", version.ref = "semver" }
zoomable = { module = "com.mxalbert.zoomable:zoomable", version.ref = "zoomable" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
