name: Build Docker Web Image

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-docker.yml'
      - 'composeApp/src/commonMain/**'
      - 'composeApp/src/wasmJsMain/**'
      - '**/*.gradle.kts'
      - '*.properties'
      - 'gradle/**'
  release:
    types:
      - released

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - name: Write local.properties
        shell: bash
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > local.properties

      - name: Build AAB
        id: build_aab
        env:
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_ALIAS_PASSWORD: ${{ secrets.KEYSTORE_ALIAS_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          BASE_URL: https://escalaralcoiaicomtat.com
        run: ./gradlew :composeApp:wasmJsBrowserDistribution --no-daemon

      - name: Build and push production
        uses: docker/build-push-action@v6
        if: ${{ github.event_name == 'release' }}
        with:
          push: true
          tags: arnyminerz/escalaralcoiaicomtat-web:latest
      - name: Build and push development
        uses: docker/build-push-action@v6
        if: ${{ github.event_name != 'release' }}
        with:
          push: true
          tags: arnyminerz/escalaralcoiaicomtat-web:development
