name: Build Docker Web Image

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-docker.yml'
      - 'composeApp/src/commonMain/**'
      - 'composeApp/src/wasmJsMain/**'
      - '**/*.gradle.kts'
      - '*.properties'
      - 'gradle/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build distribution
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN_PLATFORM }}
        run: |
          ./gradlew :composeApp:wasmJsBrowserDevelopmentExecutableDistribution --stacktrace --no-daemon

      - name: Build and push development
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: arnyminerz/escalaralcoiaicomtat-web:development
          # There's an issue when building the regular Dockerfile, so build manually, and then push
          # the standalone image
          file: standalone.Dockerfile
