name: Build Docker Web Image

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-docker.yml'
      - 'composeApp/commonMain/**'
      - 'composeApp/wasmJsMain/**'
      - '**/*.gradle.kts'
      - '*.properties'
      - 'gradle/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Otherwise, build and push the development image, tagging it as development
      - name: Build and push development
        uses: docker/build-push-action@v6
        if: ${{ github.event_name != 'release' }}
        with:
          push: true
          tags: arnyminerz/escalaralcoiaicomtat-web:development
