name: Release Binaries

on:
  release:

jobs:
  update-version-name:
    name: Update version name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Update version name
        run: python ./scripts/updateVersionName.py --name=${{ github.event.release.name }}

      - name: Increase version code
        id: increase_version_code
        run: python ./scripts/increaseVersionCode.py

      - name: Commit modified version code file
        id: commit_version_code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Updated Version'
          file_pattern: 'version.properties iosApp/iosApp.xcodeproj/project.pbxproj iosApp/iosApp/Info.plist'
          branch: master

  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    needs: update-version-name

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - name: Decode Keystore
        run: |
          echo ${{ secrets.KEYSTORE_BASE64 }} > keystore.txt
          base64 --decode keystore.txt > keystore.jks

      - name: Decode google-services.json
        run: |
          echo ${{ secrets.GOOGLE_SERVICES_BASE64 }} > google-services.base64
          base64 --decode google-services.base64 > composeApp/google-services.json

      - name: Write local.properties
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > local.properties

      - name: Build AAB
        id: build_aab
        env:
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_ALIAS_PASSWORD: ${{ secrets.KEYSTORE_ALIAS_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: ./gradlew :composeApp:bundleRelease :composeApp:assembleRelease

      - name: Release AAB & APK
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./composeApp/build/outputs/**/*.aab
            ./composeApp/build/outputs/**/*.apk

  build-desktop:
    name: Build for Desktop
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    needs: update-version-name

    steps:
      - uses: actions/checkout@v4

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - name: Write local.properties
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > local.properties

      - name: Build
        run: ./gradlew :composeApp:packageReleaseDistributionForCurrentOS

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            composeApp/build/compose/binaries/main-release/**/*.dmg
            composeApp/build/compose/binaries/main-release/**/*.msi
            composeApp/build/compose/binaries/main-release/**/*.deb

  build-wasm:
    name: Build for Web
    runs-on: ubuntu-latest

    needs: update-version-name

    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build distribution
        run: |
          ./gradlew :composeApp:wasmJsBrowserDistribution --stacktrace --no-daemon

      # Build and push the release image, tagging it as latest and the release tag
      - name: Build and push release
        uses: docker/build-push-action@v6
        if: ${{ github.event_name == 'release' }}
        with:
          push: true
          tags: arnyminerz/escalaralcoiaicomtat-web:latest,arnyminerz/escalaralcoiaicomtat-web:${{ github.event.release.tag_name }}
          # There's an issue when building the regular Dockerfile, so build manually, and then push
          # the standalone image
          file: standalone.Dockerfile
