name: Release Binaries

on:
  release:
    types:
      - released

jobs:
  update-version-name:
    name: Update version name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Update version name
        run: python ./scripts/updateVersionName.py --name=${{ github.event.release.name }}

      - name: Increase version code
        id: increase_version_code
        run: python ./scripts/increaseVersionCode.py

      - name: Commit modified version code file
        id: commit_version_code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Updated Version'
          file_pattern: 'version.properties iosApp/iosApp.xcodeproj/project.pbxproj iosApp/iosApp/Info.plist composeApp/src/commonMain/composeResources/values-*/strings.xml'
          branch: master

  clean-resources:
    name: Clean resource files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Clean quote backslashes
        id: clean_backslash
        run: bash ./scripts/clean-backslash.sh

      - name: Commit modified files
        id: commit_files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Updated Version'
          file_pattern: 'version.properties strings.xml'
          branch: master

  update-credits:
    name: Update Translation credits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Update credits file
        id: update_credits
        run: bash ./scripts/download-weblate-credits.sh

      - name: Commit modified files
        id: commit_files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Updated credits'
          file_pattern: 'credits.json'
          branch: master

  create-sentry-release:
    name: Create Sentry release
    runs-on: ubuntu-latest
    steps:
      - name: Create production Sentry release for Platform
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: 'escalar-alcoia-i-comtat'
          SENTRY_PROJECT: 'platform'
        with:
          environment: production
          release: ${{ github.event.release.tag_name }}
      - name: Create production Sentry release for Web
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: 'escalar-alcoia-i-comtat'
          SENTRY_PROJECT: 'web'
        with:
          environment: production
          release: ${{ github.event.release.tag_name }}

  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    needs: [update-version-name, clean-resources, update-credits]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Job set up
        uses: ./.github/actions/job-set-up

      # Refresh the version name again just in case
      - name: Update version name
        run: python ./scripts/updateVersionName.py --name=${{ github.event.release.name }}

      - name: Decode Keystore
        run: |
          echo ${{ secrets.KEYSTORE_BASE64 }} > keystore.txt
          base64 --decode keystore.txt > keystore.jks

      - name: Decode google-services.json
        run: |
          echo ${{ secrets.GOOGLE_SERVICES_BASE64 }} > google-services.base64
          base64 --decode google-services.base64 > composeApp/google-services.json

      - name: Write local.properties
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > local.properties

      - name: Build AAB
        id: build_aab
        env:
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_ALIAS_PASSWORD: ${{ secrets.KEYSTORE_ALIAS_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: ./gradlew :composeApp:bundleRelease :composeApp:assembleRelease

      - name: Release AAB & APK
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./composeApp/build/outputs/**/*.aab
            ./composeApp/build/outputs/**/*.apk

      - name: Upload to Play Store
        id: upload_play_store
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_GOOGLE_CLOUD_JSON }}
          packageName: org.escalaralcoiaicomtat.android
          releaseFiles: ./composeApp/build/outputs/bundle/release/composeApp-release.aab
          track: "production"
          inAppUpdatePriority: 2
          # mappingFile: ./base/build/outputs/mapping/release/mapping.txt
          # whatsNewDirectory: ./changelog
          status: completed

  build-desktop:
    name: Build for Desktop
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, macos-latest, windows-latest]

    needs: [update-version-name, clean-resources, update-credits]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Job set up
        uses: ./.github/actions/job-set-up

      # Refresh the version name again just in case
      - name: Update version name
        run: python ./scripts/updateVersionName.py --name=${{ github.event.release.name }}


      - name: Write local.properties
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > local.properties

      - name: Build
        run: ./gradlew :composeApp:packageReleaseDistributionForCurrentOS

      - name: Rename deb
        if: startsWith(matrix.os, 'ubuntu')
        run: mv composeApp/build/compose/binaries/main-release/deb/*.deb composeApp/build/compose/binaries/main-release/deb/escalar-alcoia-i-comtat_${{ matrix.os }}_amd64.deb

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            composeApp/build/compose/binaries/main-release/**/*.dmg
            composeApp/build/compose/binaries/main-release/**/*.exe
            composeApp/build/compose/binaries/main-release/**/*.deb

  build-java:
    name: Build for Java
    runs-on: ubuntu-latest

    needs: [update-version-name, clean-resources, update-credits]
    # Disable jar release
    if: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Job set up
        uses: ./.github/actions/job-set-up

      # Refresh the version name again just in case
      - name: Update version name
        run: python ./scripts/updateVersionName.py --name=${{ github.event.release.name }}


      - name: Write local.properties
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > local.properties

      - name: Build
        run: ./gradlew :composeApp:packageReleaseUberJarForCurrentOS

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            composeApp/build/compose/jars/*.jar

  build-wasm:
    name: Build for Web
    runs-on: ubuntu-latest

    needs: [update-version-name, clean-resources, update-credits]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      # Refresh the version name again just in case
      - name: Update version name
        run: python ./scripts/updateVersionName.py --name=${{ github.event.release.name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build distribution
        run: |
          ./gradlew :composeApp:wasmJsBrowserDevelopmentExecutableDistribution --stacktrace --no-daemon

      # Build and push the release image, tagging it as latest and the release tag
      - name: Build and push release
        uses: docker/build-push-action@v6
        if: ${{ github.event_name == 'release' }}
        with:
          push: true
          tags: arnyminerz/escalaralcoiaicomtat-web:latest,arnyminerz/escalaralcoiaicomtat-web:${{ github.event.release.tag_name }}
          # There's an issue when building the regular Dockerfile, so build manually, and then push
          # the standalone image
          file: standalone.Dockerfile
